### PR TITLE
feat: add Timezone via build argument

### PR DESCRIPTION
**Pull request by shantanoo-desai**

### CODE REVIEW

**Comment by jockebech** [comment]
Hi @shantanoo-desai , no particular reason to the question you asked. I haven't cared that much about the timezone. Can you please squash all patches to a single patch. Seems like you've been adding and removing things in the series, so by having it all squashed it is easier to see what actually is done.

**Comment by shantanoo-desai** [comment]
@jbech-linaro  thanks for reaching out. For the squash, since you are the owner of the repository, you can click on the drop-down menu for the Merge Pull Request and squash these commits all together. If that doesn't work, let me know I will squash from my end

**Comment by jockebech** [comment]
> @jbech-linaro thanks for reaching out. For the squash, since you are the owner of the repository, you can click on the drop-down menu for the Merge Pull Request and squash these commits all together. If that doesn't work, let me know I will squash from my end

Right, but if I do that, then there is I have to make sure that the git commit message etc is correct. Other at the OP-TEE project we've always only used "rebase and merge". That gives a clean history (no merge commits) and the author is in charge of all patch work. So, please squash and then force push to the same branch.

**Comment by shantanoo-desai** [comment]
sorry for the bother again, please let me know if this is what is required. I have squashed the changes into one commit as requested. However not sure if you want me to create a new PR.

**Comment by jockebech** [comment]
No need for any new PR. In short, this is what is needed.
1. git rebase -i first-commit^1 (select "f" on all but the first)
2. git commit --amend (and write a good commit message)
3. git push -f <shantanoo-desai:master>

With that this PR should be updated to only have a single commit with a good commit message and I could just do a "rebase and merge" without any conflicts and a clean git history.

**Comment by shantanoo-desai** [comment]
Thanks for your patience and help. I will give the container one last test on my machines and check if the dependencies are working accordingly and try rebasing this PR as per the requirements.

**Comment by jockebech** [comment]
No problem, speaking about the timezone issues. I've dealt with that in another way in my other branches, see here for example: https://github.com/jbech-linaro/docker_optee/blob/cached-ubuntu-20.04/Dockerfile#L6-L8. The non-master branches have been the ones that I've been using mostly, since they leverage ccache and repo forest from my host. I.e., setting up those are much faster.

**Comment by jockebech** [comment]
@shantanoo-desai , I've added the packages suggested in #3 , with that I did a test build and everything worked as expected. So for building and running the master branch should be OK now. The timezone is what is left I suppose. If you feel that it is useful to submit that from the host or via arguments, then I'd be happy to merge that.

**Comment by shantanoo-desai** [comment]
hello @jbech-linaro I think it is okay from my side. I can close this PR. We can prioritize maybe a simple change to `README.md` in terms of changing the timezone information.

**Comment by jockebech** [comment]
Sure, I can bring in the changes I have on the other branch as well, that is easier and more correct way of doing it I suppose.

**Comment by jockebech** [comment]
FYI, I've updated the two other branches now as well. So all these should be working now.

```
cached-ubuntu-20.04 (hardcoded paths for my laptop, need to change run.sh)
ubuntu-20.04
master
```

**Pull request closed without merging**
